### ISSUE TITLE
Reports dependency mods are missing when they're not

### ISSUE THREAD

**Issue by NHellFire** [JamesWilko/Payday-2-BLT-Lua#10]
On startup, I'm being told I'm missing Announcer & Fading Contour even though they are installed (and up-to-date).

Log attached. Using BLT-Lua 0c62569
[2017_04_23_log.txt](https://github.com/JamesWilko/Payday-2-BLT-Lua/files/949735/2017_04_23_log.txt)

**Comment by JamesWilko** [comment]
Dependencies have been rewritten, so this should no longer occur.
