### ISSUE TITLE
Choose lang - not work

### ISSUE THREAD

**Issue by chromKa** [JamesWilko/Payday-2-BLT-Lua#17]
Please fix this problem.

**Comment by justalemon** [comment]
Yep, the language change is not working (at least for me, fresh BLT install).

**Comment by justalemon** [comment]
The same problem here, even if the lang code  into "mods/saves/blt_data.txt"
```
{"keybinds":[],"mods":{"base":{"enabled":true,"updates":{"payday2bltdll":true,"payday2blt":true},"safe":false}},"language":"es"}
```

**Comment by TakRiuto** [comment]
Yep, BLT 2.1 and 2.2 is ignored the blt_data.txt, if you delete that file, the BLT dont make another, is a problem read/write that file

**Comment by JamesWilko** [comment]
Fixed in https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/c2cddbd277d046b38dcab67409bbd20897cd2a45 and https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/169a7d3439b52847aba06ad95a7c961d7d06556e.
