### ISSUE TITLE
BLT options only in main menu?

### ISSUE THREAD

**Issue by Luffyyy** [JamesWilko/Payday-2-BLT-Lua#27]
Why is BLT creating the options menu node only in main menu there are clearly mods that use the options menu in game.

**Comment by segabl** [comment]
I'd like to know the reasoning behind that as well (it's clearly intended, looking at this commit: https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/8e16aa36777e94f9fbd8cf9991f2842fa048de9c) since some mods use ingame menus to provide a realtime preview of the settings.

**Comment by JamesWilko** [comment]
Temporary change to prevent creating nodes that weren't needed in places they weren't meant to be. It was going to be added in before launch if I had time, or as a patch.

**Comment by JamesWilko** [comment]
Added in 89240f957c22303141a50efc91d8b4b8fbc9a96c
