### ISSUE TITLE
DB:create_entry currently not availble under linux

### ISSUE THREAD

**Issue by punkkeks** [JamesWilko/Payday-2-BLT-Lua#50]
See for this: https://github.com/blt4linux/blt4l/issues/70

The thing is, that you use it in the [BLTMod.lua](https://github.com/JamesWilko/Payday-2-BLT-Lua/blob/e942134566f8f1ddcf7402302c62aa058f9b5990/mods/base/req/BLTMod.lua#L286) file. 
Can we use a current workaround like [this one](https://stackoverflow.com/questions/295052/how-can-i-determine-the-os-of-the-system-from-within-a-lua-script) to check if we are under a linux environment and just `return nil` in that function? Other mods, depending on `DB:create_entry` just not work by now iirc. But for now, it would be a nice to have function, so you could use the same mods folder structure for windows and linux.

**Comment by Luffyyy** [comment]
Mostly you can blame overkill for not implementing that function.

**Comment by ZNixian** [comment]
Checking `BLT.PlatformName` would be the easiest way if you want to nil it out, though I believe RomanHargrave is working on adding that.

**Comment by Luffyyy** [comment]
This is the best way of doing it https://github.com/JamesWilko/Payday-2-BLT-Lua/issues/52#issuecomment-327919680

**Comment by JamesWilko** [comment]
Mod images will no longer be created if DB.create_entry does not exist. https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/54fd0a0f1e097a63c6a9defe106c60af0d38c013
